### ISSUE TITLE
Add example backend service

### ISSUE THREAD

**Issue by philhug** [Nordstrom/kubernetes-vulcand-router#3]
It would be nice to also have an example service file. I seem to have problems getting it to work:

```
kind: Service
apiVersion: v1
metadata:
  name: test-vulcand-proxy
  annotations:
    vulcand.io/routed: "true"
    vulcand.io/route: Host("example.com")
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: test
  type: ClusterIP
  ClusterIP: None
```

time="2015-11-20T14:39:07Z" level=info msg="Adding service" serviceID=default-test-vulcand-proxy 
time="2015-11-20T14:39:07Z" level=warning msg="Unable to find service for endpoint" name=test-vulcand-proxy namespace=default 
time="2015-11-20T14:39:07Z" level=warning msg="Could not get endpoints for service" error=<nil> serviceID=default-test-vulcand-proxy
